### PR TITLE
Add HTML validator to the repository

### PR DESCRIPTION
**Pull request by molnard**
Also to try GitHub actions. I may have improved. 

It is using this: https://github.com/marketplace/actions/html5-validator

### CODE REVIEW

**Comment by molnard** [comment]
@RiccardoMasutti can you check this? Does this make sense? 

image

https://github.com/zkSNACKs/zkSNACKsSite/pull/11/checks?check_run_id=1133940885

**Comment by RiccardoMasutti** [comment]
It appears this validator is out of date. In fact it does not recognize the `loading="lazy"` variable for images.

I prefer the [w3 validator](https://validator.w3.org/)

**Comment by molnard** [comment]
I could not find a GitHub app, GitHub action, or script to integrate it with GitHub

**Comment by BTCparadigm** [comment]
Is this still relevant?

**Pull request closed without merging**
