### PR TITLE
Optimize images and videos

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Google has indicated site speed (and as a result, page speed) is [one of the signals used by its algorithm to rank pages](http://googlewebmastercentral.blogspot.com/2010/04/using-site-speed-in-web-search-ranking.html).

Page speed is also important to user experience. Pages with a longer load time tend to have higher bounce rates and lower average time on page. Longer load times have also been shown to negatively affect conversions.

Right now page size is 17.6 MB and it takes 5.62 to load from a Frankfurt server. This PR optimize compress and optimize images and videos.
Screenshot_2020-09-16 Pingdom Tools

### CODE REVIEW

**Comment by molnard** [comment]
@Rmartin1104 can you take a look?

**Review by yahiheb — COMMENTED** [review]
Shouldn't `wwwroot/assets/bg2.webm` get removed?

**Comment by RiccardoMasutti** [comment]
> Shouldn't `wwwroot/assets/bg2.webm` get removed?

Yes thank you!

**Comment by molnard** [comment]
hmm, video quality decreased a lot - it is not looking good.

**Comment by RiccardoMasutti** [comment]
@molnard yes, but we cannot have a 10MB video in the website. 2MB is already a lot.

Maybe we should use something like https://vincentgarreau.com/particles.js/

**Comment by molnard** [comment]
Yes definitely! Can you make it work?

**Comment by RiccardoMasutti** [comment]
@molnard it will take some time but I can work on it.
I used it in the past for multiple websites

**Comment by RiccardoMasutti** [comment]
> Yes definitely! Can you make it work?

What if we just use `/assets/bg2_video_poster.png` without videos/animations?

**Comment by molnard** [comment]
Yes, can you change it?

**Comment by RiccardoMasutti** [comment]
@molnard can you review it now?

**Comment by yahiheb** [comment]
Remove the `wwwroot/assets/bg2.mp4` file.

**Review by molnard — APPROVED** [review]
Well done

**Pull request merged**
