### PR TITLE
4 pictures changed

### PR DESCRIPTION
**Pull request by Rmartin1104**
@molnard   Can you check it please?

### CODE REVIEW

**Comment by molnard** [comment]
LGTM continue.

**Comment by molnard** [comment]
Why it is so grey, the opacity is changed? 

image

**Review by molnard — CHANGES_REQUESTED** [review]
- Picture sizes different, they disrupt the layout. 
- Names capitalization should be the same. 

image

**Comment by molnard** [comment]
Is this ready to review?

**Comment by Rmartin1104** [comment]
I did all changes. But if you found something else i will do. If not Yes ready.

**Comment by molnard** [comment]
Jumar looks like a dwarf. Can you crop the picture into the appropriate size instead of shrinking it?
Don't forget to sync in github desktop I made some changes here. 

image

**Comment by molnard** [comment]
Tested ACK

**Pull request merged**
